module.exports = {
  AUTH_LOGS: 'auth_logs',
  DEVICE_MANAGER: 'device_manager',
  INVENTORY_GROUPS: 'inventory_groups',
  INVENTORY_ITEMS: 'inventory_items',
  KOT_STATIONS: 'kot_stations',
  LOGINS: 'logins',
  MASTER_CITY: 'master_city',
  MASTER_COUNTRY: 'master_country',
  MASTER_STATE: 'master_state',
  MASTER_UNIT: 'master_unit',
  MENU_CATEGORIES: 'menu_categories',
  MENU_ITEM_CUSTOMIZATIONS: 'menu_item_customizations',
  MENU_ITEM_QUANTITY_PRICE: 'menu_item_quantity_price',
  MENU_ITEMS: 'menu_items',
  MENU_SECTION_MAPPINGS: 'menu_section_mappings',
  MENU_SUB_CATEGORIES: 'menu_sub_categories',
  ORGANIZATION_PROFILE: 'organization_profile',
  RESTO_MENUS: 'resto_menus',
  RESTO_SECTIONS: 'resto_sections',
  ROLES: 'roles',
  SHIFTS: 'shifts',
  SECTION_TABLES: 'section_tables',
  USER_ROLE_MAPPINGS: 'user_role_mappings',
  USER_SHIFT_MAPPINGS: 'user_shift_mappings',
  USERS: 'users'
};
